#!/bin/bash

VERSION="1.3"

# list pipeline & select one
function pipeline_list () {
    mapfile -t pipelines <<< `tkn p list $NS_OPT | grep -v '^NAME' | awk '{print $1}'`
    if [ ${pipelines[0]} = "No" ]; then
        echo "No Pipeline found. Exit"
        exit 1
    fi

    echo ""
    PS3="Select Pipeline (or 'q' to quit)> "
    select PIPELINE in "${pipelines[@]}"
    do
        if [ "${REPLY}" = "q" ]; then
            exit 0
        elif [ -n "$PIPELINE" ]; then
            break
        fi
    done
}

# list pipelinerun & select one
function pipelinerun_list () {
    mapfile -t list <<< `tkn pr list $NS_OPT $PIPELINE -o json | jq -r '.items | .[] | .metadata | select(has("generateName")|not) | .name'`
    if [ -z "${list[0]}" ]; then
        echo "No PipelineRun to match '$PIPELINE'. Exit"
        exit 1
    elif [ ${list[0]} = "No" ]; then
        echo "No Pipeline: $PIPELINE. Exit"
        exit 1
    fi

    echo ""
    PS3='Select PipelineRun (or 'q' to quit)> '
    select PR in "${list[@]}"
    do
        if [ "${REPLY}" = "q" ]; then
            exit 0
        elif [ -n "$PR" ]; then
            break
        fi
    done
}

function task_list () {
    mapfile -t tasks <<< `tkn task list $NS_OPT | grep -v '^NAME' | awk '{print $1}'`
    if [ ${tasks[0]} = "No" ]; then
        echo "No Task found. Exit"
        exit 1
    fi

    echo ""
    PS3="Select Task (or 'q' to quit)> "
    select TASK in "${tasks[@]}"
    do
        if [ "${REPLY}" = "q" ]; then
            exit 0
        elif [ -n "$TASK" ]; then
            break
        fi
    done
}

function taskrun_list () {
    # exclude invoked from pipelines or generated with previous Taskrun.
    mapfile -t list <<< `tkn tr list $NS_OPT $TASK -o json | jq -r '.items | .[] | .metadata | select(has("generateName")|not) | select(.labels | has("tekton.dev/pipeline")|not) | .name'`
    if [ -z "${list[0]}" ]; then
        echo "No TaskRun to match '$TASK'. Exit"
        exit 1
    elif [ ${list[0]} = "No" ]; then
        echo "No Task: $TASK. Exit"
        exit 1
    fi

    echo ""
    PS3='Select TaskRun (or 'q' to quit)> '
    select TASKRUN in "${list[@]}"
    do
        if [ "${REPLY}" = "q" ]; then
            exit 0
        elif [ -n "$TASKRUN" ]; then
            break
        fi
    done
}

function show_usage () {
    echo ""
    echo "tkn-runner version $VERSION"
    echo "  Usage:    tkn runner [options] [<pipeline or task name>]"
    echo "  Options:"
    echo "            --showlog        show logs right after starting the Pipeline|Task"
    echo "            --dry-run        preview PipelineRun|TaskRun without running it"
    echo "            -d               run 'describe' subcommand"
    echo "            -l               run 'logs' subcommand"
    echo "            -n <namespace>   Specify namespace"
    echo '            -p <stringArray> pass the param as key=value for string type, or key=value1,value2,... for array type, or key="key1:value1, key2:value2" for object type'
    echo "            -t               Use task instead of pipeline"
    echo "            -h               Show this usage"
    echo ""
    exit 1
}

# check if tkn installed
# https://github.com/tektoncd/cli
tkn version 2&> /dev/null
if [ $? -ne 0 ]; then
    echo "Tekton CLI not found. exit"
    exit 1
fi

# check if jq installed
# https://stedolan.github.io/jq/
jq --version 2&> /dev/null
if [ $? -ne 0 ]; then
  echo "jq not found. exit"
  exit 1
fi

set -eu

# set default
RUN_MODE="pipeline"
TKN_CMD="start"
LOG_OPT=""
RUN_OPT=""
if [ -v TEKTON_NS ]; then
  NS_OPT="-n $TEKTON_NS"
else
  NS_OPT=""
fi

while getopts dlhn:p:t-: OPT
do
    if [[ "$OPT" = - ]]; then
      OPT="$OPTARG"
    fi
    case $OPT in
        "d" ) TKN_CMD="describe" ;;
        "l" ) TKN_CMD="logs" ;;
        "h" ) show_usage ;;
        "n" ) NS_OPT="-n $OPTARG" ;;
        "p" ) RUN_OPT="$RUN_OPT -p $OPTARG" ;;
        "t" ) RUN_MODE="task" ;;
        "showlog" ) LOG_OPT="$LOG_OPT --showlog" ;;
        "dry-run" ) LOG_OPT="$LOG_OPT --dry-run" ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ $RUN_MODE = "task" ]; then
    if [ $# -lt 1 ]; then
        task_list
    else
        TASK=$1
    fi
    case "$TKN_CMD" in
        "start" ) taskrun_list
                  tkn task start $TASK $NS_OPT $LOG_OPT $RUN_OPT --use-taskrun $TASKRUN ;;
        "describe" | "logs" ) tkn task $TKN_CMD $TASK ;;
    esac
    exit 0
else
    if [ $# -lt 1 ]; then
        pipeline_list
    else
        PIPELINE=$1
    fi
    case "$TKN_CMD" in
        "start" ) pipelinerun_list
                  tkn pipeline start $PIPELINE $NS_OPT $LOG_OPT $RUN_OPT --use-pipelinerun $PR ;;
        "describe" | "logs" ) tkn pipeline $TKN_CMD $PIPELINE ;;
    esac
fi
